# Generated by Django 5.2.1 on 2026-04-28 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField(help_text='Escribi un ingrediente por linea o separados por coma.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('almuerzo', 'Almuerzo'), ('cena', 'Cena')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_meals', to='planner.dish')),
            ],
            options={
                'ordering': ['date', 'meal_type'],
                'constraints': [models.UniqueConstraint(fields=('date', 'meal_type'), name='unique_meal_slot_per_day')],
            },
        ),
    ]
