# Generated by Django 5.2.1 on 2026-04-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.CharField(default='1', max_length=40)),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_checked', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroceryItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('item_name', models.CharField(max_length=120)),
                ('is_checked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['item_name'],
                'constraints': [models.UniqueConstraint(fields=('week_start', 'item_name'), name='unique_grocery_item_state')],
            },
        ),
    ]
