# Generated by Django 5.2.1 on 2026-05-25 23:05

import django.db.models.deletion
import re
from decimal import Decimal, InvalidOperation
from django.db import migrations, models


def normalize_ingredient_name(name):
    clean_name = " ".join(name.strip().lower().split())
    if len(clean_name) > 3 and clean_name.endswith("s"):
        clean_name = clean_name[:-1]
    return clean_name.capitalize()


def parse_ingredient(item):
    match = re.match(
        r"^(?P<name>.+?)\s*x\s*(?P<quantity>\d+(?:[.,]\d+)?)$",
        item,
        re.IGNORECASE,
    )
    if not match:
        return item, Decimal("1")

    name = match.group("name").strip()
    raw_quantity = match.group("quantity").replace(",", ".")
    try:
        quantity = Decimal(raw_quantity)
    except InvalidOperation:
        quantity = Decimal("1")
    return name, quantity


def split_ingredients(raw_ingredients):
    raw = raw_ingredients.replace(";", "\n")
    raw = re.sub(r"(?<!\d),(?!\d)", "\n", raw)
    return [item.strip() for item in raw.splitlines() if item.strip()]


def migrate_legacy_ingredients(apps, schema_editor):
    Dish = apps.get_model("planner", "Dish")
    Ingredient = apps.get_model("planner", "Ingredient")
    DishIngredient = apps.get_model("planner", "DishIngredient")
    GroceryItemState = apps.get_model("planner", "GroceryItemState")

    ingredient_by_name = {}
    for dish in Dish.objects.all():
        for raw_item in split_ingredients(dish.ingredients or ""):
            raw_name, quantity = parse_ingredient(raw_item)
            name = normalize_ingredient_name(raw_name)
            ingredient = ingredient_by_name.get(name)
            if ingredient is None:
                ingredient, _ = Ingredient.objects.get_or_create(name=name)
                ingredient_by_name[name] = ingredient

            dish_item, created = DishIngredient.objects.get_or_create(
                dish=dish,
                ingredient=ingredient,
                defaults={"quantity": quantity},
            )
            if not created:
                dish_item.quantity += quantity
                dish_item.save(update_fields=["quantity"])

    for state in GroceryItemState.objects.exclude(item_name=""):
        name = normalize_ingredient_name(state.item_name)
        ingredient = ingredient_by_name.get(name)
        if ingredient is None:
            ingredient = Ingredient.objects.filter(name=name).first()
        if ingredient:
            existing = (
                GroceryItemState.objects.filter(
                    week_start=state.week_start,
                    ingredient=ingredient,
                )
                .exclude(pk=state.pk)
                .first()
            )
            if existing:
                existing.is_checked = existing.is_checked or state.is_checked
                existing.quantity_override = existing.quantity_override or state.quantity_override
                existing.save(update_fields=["is_checked", "quantity_override"])
                state.delete()
                continue
            state.ingredient = ingredient
            state.save(update_fields=["ingredient"])


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_groceryitemstate_quantity_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8)),
            ],
            options={
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='groceryitemstate',
            options={'ordering': ['ingredient__name', 'item_name']},
        ),
        migrations.RemoveConstraint(
            model_name='groceryitemstate',
            name='unique_grocery_item_state',
        ),
        migrations.AlterField(
            model_name='groceryitemstate',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_items', to='planner.dish'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_items', to='planner.ingredient'),
        ),
        migrations.AddField(
            model_name='groceryitemstate',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_states', to='planner.ingredient'),
        ),
        migrations.RunPython(migrate_legacy_ingredients, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddConstraint(
            model_name='groceryitemstate',
            constraint=models.UniqueConstraint(fields=('week_start', 'ingredient'), name='unique_grocery_item_state'),
        ),
        migrations.AddConstraint(
            model_name='dishingredient',
            constraint=models.UniqueConstraint(fields=('dish', 'ingredient'), name='unique_ingredient_per_dish'),
        ),
    ]
