# Generated by Django 5.2.1 on 2026-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_dishingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_type',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kg')], default='unidad', max_length=20),
        ),
    ]
